apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cs-ingress
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.global-static-ip-name: commonswap-com
    networking.gke.io/managed-certificates: commonswap-cert
spec:
  rules:
    - host: staging.commonswap.com
      http:
        paths:
          - backend:
              serviceName: cs-frontend-staging
              servicePort: 8080
